### PR TITLE
Add a workaround for iPadOS unsatisfied constraints, #75

### PR DESCRIPTION
**Pull request by Klipi**
Fixes issue #75.

### CODE REVIEW

**Comment by Klipi** [comment]
I just noticed that the built `libNatShare.a` is also in the repo. Should I add an updated version to the PR?

**Comment by olokobayusuf** [comment]
If you can please do. The Xcode project is set to copy the built `libNatShare.a` to the Unity project on build. So a simple build in Xcode is all you need to do.

**Comment by Klipi** [comment]
Done 🙂

**Comment by olokobayusuf** [comment]
Merged!

**Pull request merged**
